# Generated by Django 2.0.1 on 2018-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField()),
                ('status_message', models.TextField(blank=True, null=True)),
                ('bulk_or_delta', models.TextField()),
            ],
            options={
                'db_table': 'job_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.AutoField(primary_key=True)),
                ('function_name', models.TextField()),
                ('stage', models.TextField()),
                ('status', models.TextField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_schedule',
                'managed': False,
            },
        ),
    ]
